window.OPIC_CARDS=[
  {
    "id": 1,
    "category": "home",
    "categoryName": "집·동네",
    "korean": "우리 집은 지하철역과 가까워서 정말 편리하다.",
    "target": "편리하다",
    "answer": "convenient",
    "english": "My home is really convenient because it is close to the subway station.",
    "note": "장소나 시설 이용이 편리할 때",
    "level": "IM3-IH"
  },
  {
    "id": 2,
    "category": "home",
    "categoryName": "집·동네",
    "korean": "이 소파는 오래 앉아 있어도 편하다.",
    "target": "편하다",
    "answer": "comfortable",
    "english": "This sofa is comfortable even when I sit on it for a long time.",
    "note": "신체적으로 편안할 때",
    "level": "IM3-IH"
  },
  {
    "id": 3,
    "category": "home",
    "categoryName": "집·동네",
    "korean": "나는 집에 있을 때 가장 마음이 편하다.",
    "target": "편하다",
    "answer": "at ease",
    "english": "I feel most at ease when I am at home.",
    "note": "긴장하지 않고 마음이 편할 때",
    "level": "IM3-IH"
  },
  {
    "id": 4,
    "category": "home",
    "categoryName": "집·동네",
    "korean": "우리 동네는 밤에도 비교적 조용하다.",
    "target": "조용하다",
    "answer": "quiet",
    "english": "My neighborhood is relatively quiet even at night.",
    "note": "소리가 적을 때",
    "level": "IM3-IH"
  },
  {
    "id": 5,
    "category": "home",
    "categoryName": "집·동네",
    "korean": "주말에는 거리가 사람들로 붐빈다.",
    "target": "붐빈다",
    "answer": "crowded",
    "english": "The streets are crowded on weekends.",
    "note": "사람이 많아 복잡할 때",
    "level": "IM3-IH"
  },
  {
    "id": 6,
    "category": "home",
    "categoryName": "집·동네",
    "korean": "최근에 동네 분위기가 많이 활기차졌다.",
    "target": "활기차졌다",
    "answer": "lively",
    "english": "My neighborhood has become much more lively recently.",
    "note": "생기와 활동성이 있을 때",
    "level": "IM3-IH"
  },
  {
    "id": 7,
    "category": "home",
    "categoryName": "집·동네",
    "korean": "집 근처에 필요한 시설이 모두 갖춰져 있다.",
    "target": "갖춰져 있다",
    "answer": "well-equipped",
    "english": "The area near my home is well-equipped with everything I need.",
    "note": "시설이나 장비가 잘 마련됐을 때",
    "level": "IM3-IH"
  },
  {
    "id": 8,
    "category": "home",
    "categoryName": "집·동네",
    "korean": "내 방은 작지만 아주 아늑하다.",
    "target": "아늑하다",
    "answer": "cozy",
    "english": "My room is small but very cozy.",
    "note": "작고 따뜻하며 편안한 분위기",
    "level": "IM3-IH"
  },
  {
    "id": 9,
    "category": "home",
    "categoryName": "집·동네",
    "korean": "이 아파트는 관리가 잘 되어 있어서 깔끔하다.",
    "target": "깔끔하다",
    "answer": "well-maintained",
    "english": "This apartment is clean because it is well-maintained.",
    "note": "건물이나 시설이 잘 관리될 때",
    "level": "IM3-IH"
  },
  {
    "id": 10,
    "category": "home",
    "categoryName": "집·동네",
    "korean": "이사한 뒤 출퇴근 시간이 크게 줄었다.",
    "target": "줄었다",
    "answer": "decreased",
    "english": "My commuting time has decreased significantly since I moved.",
    "note": "수치나 양이 감소했을 때",
    "level": "IM3-IH"
  },
  {
    "id": 11,
    "category": "daily",
    "categoryName": "일상",
    "korean": "나는 평일에는 보통 일찍 일어난다.",
    "target": "일어난다",
    "answer": "get up",
    "english": "I usually get up early on weekdays.",
    "note": "잠자리에서 일어나다",
    "level": "IM3-IH"
  },
  {
    "id": 12,
    "category": "daily",
    "categoryName": "일상",
    "korean": "아침에는 시간이 없어서 식사를 자주 거른다.",
    "target": "거른다",
    "answer": "skip",
    "english": "I often skip breakfast because I do not have enough time in the morning.",
    "note": "식사나 일정을 건너뛰다",
    "level": "IM3-IH"
  },
  {
    "id": 13,
    "category": "daily",
    "categoryName": "일상",
    "korean": "퇴근 후에는 소파에 누워 잠깐 쉰다.",
    "target": "쉰다",
    "answer": "take a break",
    "english": "I take a break on the sofa after work.",
    "note": "잠시 휴식하다",
    "level": "IM3-IH"
  },
  {
    "id": 14,
    "category": "daily",
    "categoryName": "일상",
    "korean": "요즘은 규칙적으로 운동하는 습관을 기르려고 한다.",
    "target": "기르려고 한다",
    "answer": "develop",
    "english": "I am trying to develop a habit of exercising regularly.",
    "note": "습관이나 능력을 기르다",
    "level": "IM3-IH"
  },
  {
    "id": 15,
    "category": "daily",
    "categoryName": "일상",
    "korean": "나는 해야 할 일을 휴대폰 메모에 적어 둔다.",
    "target": "적어 둔다",
    "answer": "write down",
    "english": "I write down what I need to do on my phone.",
    "note": "기억하기 위해 기록하다",
    "level": "IM3-IH"
  },
  {
    "id": 16,
    "category": "daily",
    "categoryName": "일상",
    "korean": "주말에는 밀린 집안일을 한꺼번에 해치운다.",
    "target": "해치운다",
    "answer": "get done",
    "english": "I get all my pending chores done on weekends.",
    "note": "해야 할 일을 완료하다",
    "level": "IM3-IH"
  },
  {
    "id": 17,
    "category": "daily",
    "categoryName": "일상",
    "korean": "나는 약속 시간보다 조금 일찍 도착하는 편이다.",
    "target": "도착하는 편이다",
    "answer": "tend to arrive",
    "english": "I tend to arrive a little earlier than the scheduled time.",
    "note": "그런 경향이 있다고 말할 때",
    "level": "IM3-IH"
  },
  {
    "id": 18,
    "category": "daily",
    "categoryName": "일상",
    "korean": "피곤하면 집중력이 쉽게 떨어진다.",
    "target": "떨어진다",
    "answer": "drop",
    "english": "My concentration tends to drop when I am tired.",
    "note": "수준이나 능력이 낮아질 때",
    "level": "IM3-IH"
  },
  {
    "id": 19,
    "category": "daily",
    "categoryName": "일상",
    "korean": "중요한 일정은 미리 알람을 설정한다.",
    "target": "설정한다",
    "answer": "set",
    "english": "I set an alarm in advance for important schedules.",
    "note": "기기나 조건을 설정하다",
    "level": "IM3-IH"
  },
  {
    "id": 20,
    "category": "daily",
    "categoryName": "일상",
    "korean": "바쁜 날에는 계획대로 일이 진행되지 않는다.",
    "target": "진행되지 않는다",
    "answer": "go as planned",
    "english": "Things do not go as planned on busy days.",
    "note": "계획한 방식대로 진행되다",
    "level": "IM3-IH"
  },
  {
    "id": 21,
    "category": "food",
    "categoryName": "음식·카페",
    "korean": "이 식당은 음식 양이 정말 푸짐하다.",
    "target": "푸짐하다",
    "answer": "generous",
    "english": "The portions at this restaurant are very generous.",
    "note": "음식 양이 많고 넉넉할 때",
    "level": "IM3-IH"
  },
  {
    "id": 22,
    "category": "food",
    "categoryName": "음식·카페",
    "korean": "이 찌개는 생각보다 훨씬 매콤하다.",
    "target": "매콤하다",
    "answer": "spicy",
    "english": "This stew is much spicier than I expected.",
    "note": "매운맛이 강할 때",
    "level": "IM3-IH"
  },
  {
    "id": 23,
    "category": "food",
    "categoryName": "음식·카페",
    "korean": "고기가 아주 부드럽고 촉촉하다.",
    "target": "촉촉하다",
    "answer": "juicy",
    "english": "The meat is very tender and juicy.",
    "note": "고기나 과일에 수분이 많을 때",
    "level": "IM3-IH"
  },
  {
    "id": 24,
    "category": "food",
    "categoryName": "음식·카페",
    "korean": "튀김은 겉이 바삭하고 속은 부드럽다.",
    "target": "부드럽다",
    "answer": "soft",
    "english": "The fried food is crispy outside and soft inside.",
    "note": "질감이 단단하지 않을 때",
    "level": "IM3-IH"
  },
  {
    "id": 25,
    "category": "food",
    "categoryName": "음식·카페",
    "korean": "이 카페는 디저트 종류가 다양하다.",
    "target": "다양하다",
    "answer": "varied",
    "english": "This cafe has a varied selection of desserts.",
    "note": "종류나 선택지가 여러 가지일 때",
    "level": "IM3-IH"
  },
  {
    "id": 26,
    "category": "food",
    "categoryName": "음식·카페",
    "korean": "나는 새로운 식당을 찾아다니는 것을 좋아한다.",
    "target": "좋아한다",
    "answer": "enjoy",
    "english": "I enjoy looking for new restaurants.",
    "note": "활동 자체를 즐길 때",
    "level": "IM3-IH"
  },
  {
    "id": 27,
    "category": "food",
    "categoryName": "음식·카페",
    "korean": "주말 저녁에는 인기 식당을 미리 예약해야 한다.",
    "target": "예약해야 한다",
    "answer": "make a reservation",
    "english": "You need to make a reservation at popular restaurants on weekend evenings.",
    "note": "식당·호텔 자리를 예약하다",
    "level": "IM3-IH"
  },
  {
    "id": 28,
    "category": "food",
    "categoryName": "음식·카페",
    "korean": "음식이 너무 늦게 나와서 직원에게 물어봤다.",
    "target": "물어봤다",
    "answer": "asked",
    "english": "The food was taking too long, so I asked a staff member about it.",
    "note": "정보나 상황을 질문하다",
    "level": "IM3-IH"
  },
  {
    "id": 29,
    "category": "food",
    "categoryName": "음식·카페",
    "korean": "그 식당은 가격에 비해 음식이 괜찮다.",
    "target": "괜찮다",
    "answer": "decent",
    "english": "The food at that restaurant is decent for the price.",
    "note": "아주 훌륭하진 않아도 충분히 괜찮을 때",
    "level": "IM3-IH"
  },
  {
    "id": 30,
    "category": "food",
    "categoryName": "음식·카페",
    "korean": "식사를 마친 뒤 계산을 따로 나눠서 했다.",
    "target": "나눠서 했다",
    "answer": "split the bill",
    "english": "We split the bill after finishing our meal.",
    "note": "비용을 나누어 계산하다",
    "level": "IM3-IH"
  },
  {
    "id": 31,
    "category": "travel",
    "categoryName": "여행·호텔",
    "korean": "여행을 가기 전에 숙소를 미리 알아본다.",
    "target": "알아본다",
    "answer": "look into",
    "english": "I look into accommodations before going on a trip.",
    "note": "자세히 조사하다",
    "level": "IM3-IH"
  },
  {
    "id": 32,
    "category": "travel",
    "categoryName": "여행·호텔",
    "korean": "호텔이 해변에서 걸어서 갈 수 있는 거리에 있다.",
    "target": "거리에 있다",
    "answer": "within walking distance",
    "english": "The hotel is within walking distance of the beach.",
    "note": "걸어서 갈 수 있을 만큼 가까울 때",
    "level": "IM3-IH"
  },
  {
    "id": 33,
    "category": "travel",
    "categoryName": "여행·호텔",
    "korean": "비행기가 날씨 때문에 두 시간 지연되었다.",
    "target": "지연되었다",
    "answer": "was delayed",
    "english": "The flight was delayed for two hours because of the weather.",
    "note": "출발이나 일정이 늦춰지다",
    "level": "IM3-IH"
  },
  {
    "id": 34,
    "category": "travel",
    "categoryName": "여행·호텔",
    "korean": "나는 여행할 때 유명한 관광지보다 현지 분위기를 즐기는 편이다.",
    "target": "즐기는 편이다",
    "answer": "tend to enjoy",
    "english": "I tend to enjoy the local atmosphere rather than famous tourist attractions.",
    "note": "보통 그러는 경향",
    "level": "IM3-IH"
  },
  {
    "id": 35,
    "category": "travel",
    "categoryName": "여행·호텔",
    "korean": "숙소에서 제공하는 조식이 가격에 포함되어 있었다.",
    "target": "포함되어 있었다",
    "answer": "included",
    "english": "Breakfast provided by the hotel was included in the price.",
    "note": "가격이나 구성에 들어 있을 때",
    "level": "IM3-IH"
  },
  {
    "id": 36,
    "category": "travel",
    "categoryName": "여행·호텔",
    "korean": "방에 문제가 있어서 프런트에 다른 방을 요청했다.",
    "target": "요청했다",
    "answer": "requested",
    "english": "There was a problem with the room, so I requested another one at the front desk.",
    "note": "정중하고 공식적으로 요구하다",
    "level": "IM3-IH"
  },
  {
    "id": 37,
    "category": "travel",
    "categoryName": "여행·호텔",
    "korean": "여행 중에 우연히 멋진 카페를 발견했다.",
    "target": "발견했다",
    "answer": "came across",
    "english": "I came across a great cafe during my trip.",
    "note": "우연히 발견하거나 마주치다",
    "level": "IM3-IH"
  },
  {
    "id": 38,
    "category": "travel",
    "categoryName": "여행·호텔",
    "korean": "그곳의 야경은 말로 표현하기 어려울 만큼 인상적이었다.",
    "target": "인상적이었다",
    "answer": "impressive",
    "english": "The night view there was incredibly impressive.",
    "note": "강한 좋은 인상을 줄 때",
    "level": "IM3-IH"
  },
  {
    "id": 39,
    "category": "travel",
    "categoryName": "여행·호텔",
    "korean": "계획에 없던 비가 와서 일정을 바꿔야 했다.",
    "target": "바꿔야 했다",
    "answer": "had to change",
    "english": "It rained unexpectedly, so I had to change my plans.",
    "note": "상황 때문에 변경이 필요했을 때",
    "level": "IM3-IH"
  },
  {
    "id": 40,
    "category": "travel",
    "categoryName": "여행·호텔",
    "korean": "짧은 여행이었지만 스트레스를 푸는 데 도움이 되었다.",
    "target": "도움이 되었다",
    "answer": "helped",
    "english": "It was a short trip, but it helped me relieve stress.",
    "note": "무언가에 도움이 되다",
    "level": "IM3-IH"
  },
  {
    "id": 41,
    "category": "entertainment",
    "categoryName": "영화·음악",
    "korean": "그 영화는 결말이 정말 예상 밖이었다.",
    "target": "예상 밖이었다",
    "answer": "unexpected",
    "english": "The ending of the movie was completely unexpected.",
    "note": "예측과 달랐을 때",
    "level": "IM3-IH"
  },
  {
    "id": 42,
    "category": "entertainment",
    "categoryName": "영화·음악",
    "korean": "배우들의 연기가 매우 자연스러웠다.",
    "target": "자연스러웠다",
    "answer": "natural",
    "english": "The actors' performances were very natural.",
    "note": "억지스럽거나 어색하지 않을 때",
    "level": "IM3-IH"
  },
  {
    "id": 43,
    "category": "entertainment",
    "categoryName": "영화·음악",
    "korean": "그 노래를 들으면 옛날 생각이 난다.",
    "target": "난다",
    "answer": "reminds me of",
    "english": "That song reminds me of the past.",
    "note": "어떤 기억을 떠올리게 하다",
    "level": "IM3-IH"
  },
  {
    "id": 44,
    "category": "entertainment",
    "categoryName": "영화·음악",
    "korean": "나는 긴 영화를 보면 중간에 집중력을 잃는다.",
    "target": "잃는다",
    "answer": "lose focus",
    "english": "I lose focus in the middle of long movies.",
    "note": "집중하지 못하게 되다",
    "level": "IM3-IH"
  },
  {
    "id": 45,
    "category": "entertainment",
    "categoryName": "영화·음악",
    "korean": "콘서트장은 팬들로 가득 차서 분위기가 뜨거웠다.",
    "target": "뜨거웠다",
    "answer": "electric",
    "english": "The concert hall was full of fans, and the atmosphere was electric.",
    "note": "흥분되고 에너지 넘치는 분위기",
    "level": "IM3-IH"
  },
  {
    "id": 46,
    "category": "entertainment",
    "categoryName": "영화·음악",
    "korean": "요즘에는 스트리밍 서비스로 영화를 쉽게 볼 수 있다.",
    "target": "볼 수 있다",
    "answer": "access",
    "english": "These days, we can easily access movies through streaming services.",
    "note": "콘텐츠나 정보에 접근하다",
    "level": "IM3-IH"
  },
  {
    "id": 47,
    "category": "entertainment",
    "categoryName": "영화·음악",
    "korean": "그 드라마는 이야기가 너무 느리게 전개된다.",
    "target": "전개된다",
    "answer": "develops",
    "english": "The story of the drama develops too slowly.",
    "note": "이야기나 상황이 진행되다",
    "level": "IM3-IH"
  },
  {
    "id": 48,
    "category": "entertainment",
    "categoryName": "영화·음악",
    "korean": "나는 영화를 보기 전에 평점을 확인한다.",
    "target": "확인한다",
    "answer": "check",
    "english": "I check the ratings before watching a movie.",
    "note": "정보나 상태를 확인하다",
    "level": "IM3-IH"
  },
  {
    "id": 49,
    "category": "entertainment",
    "categoryName": "영화·음악",
    "korean": "주인공의 상황에 쉽게 공감할 수 있었다.",
    "target": "공감할 수 있었다",
    "answer": "relate to",
    "english": "I could easily relate to the main character's situation.",
    "note": "경험이나 감정을 공감하다",
    "level": "IM3-IH"
  },
  {
    "id": 50,
    "category": "entertainment",
    "categoryName": "영화·음악",
    "korean": "그 영화는 여러 번 봐도 질리지 않는다.",
    "target": "질리지 않는다",
    "answer": "never gets old",
    "english": "That movie never gets old even after several viewings.",
    "note": "반복해도 싫증 나지 않다",
    "level": "IM3-IH"
  },
  {
    "id": 51,
    "category": "exercise",
    "categoryName": "운동·산책",
    "korean": "운동을 시작한 뒤 체력이 많이 좋아졌다.",
    "target": "좋아졌다",
    "answer": "improved",
    "english": "My stamina has improved a lot since I started exercising.",
    "note": "능력이나 상태가 향상되다",
    "level": "IM3-IH"
  },
  {
    "id": 52,
    "category": "exercise",
    "categoryName": "운동·산책",
    "korean": "처음에는 달리기가 힘들었지만 점점 익숙해졌다.",
    "target": "익숙해졌다",
    "answer": "got used to",
    "english": "Running was difficult at first, but I gradually got used to it.",
    "note": "새로운 것에 적응하다",
    "level": "IM3-IH"
  },
  {
    "id": 53,
    "category": "exercise",
    "categoryName": "운동·산책",
    "korean": "나는 스트레스를 받으면 공원에서 산책하며 기분을 푼다.",
    "target": "푼다",
    "answer": "clear my head",
    "english": "I clear my head by taking a walk in the park when I feel stressed.",
    "note": "복잡한 생각을 정리하고 기분을 전환하다",
    "level": "IM3-IH"
  },
  {
    "id": 54,
    "category": "exercise",
    "categoryName": "운동·산책",
    "korean": "비가 오면 야외 운동 대신 집에서 운동한다.",
    "target": "운동한다",
    "answer": "work out",
    "english": "When it rains, I work out at home instead of exercising outdoors.",
    "note": "운동하다",
    "level": "IM3-IH"
  },
  {
    "id": 55,
    "category": "exercise",
    "categoryName": "운동·산책",
    "korean": "무리하게 운동하면 다음 날 근육이 뻐근하다.",
    "target": "뻐근하다",
    "answer": "sore",
    "english": "My muscles are sore the next day if I exercise too hard.",
    "note": "운동 후 근육이 아프고 뻣뻣할 때",
    "level": "IM3-IH"
  },
  {
    "id": 56,
    "category": "exercise",
    "categoryName": "운동·산책",
    "korean": "공원에는 운동할 수 있는 시설이 잘 마련되어 있다.",
    "target": "마련되어 있다",
    "answer": "available",
    "english": "There are plenty of exercise facilities available in the park.",
    "note": "사용할 수 있도록 존재할 때",
    "level": "IM3-IH"
  },
  {
    "id": 57,
    "category": "exercise",
    "categoryName": "운동·산책",
    "korean": "나는 혼자 운동하는 것보다 친구와 함께하는 것을 선호한다.",
    "target": "선호한다",
    "answer": "prefer",
    "english": "I prefer working out with a friend to exercising alone.",
    "note": "둘 중 하나를 더 좋아하다",
    "level": "IM3-IH"
  },
  {
    "id": 58,
    "category": "exercise",
    "categoryName": "운동·산책",
    "korean": "꾸준히 운동하려면 현실적인 목표를 세워야 한다.",
    "target": "세워야 한다",
    "answer": "set",
    "english": "You need to set realistic goals to exercise consistently.",
    "note": "목표나 계획을 정하다",
    "level": "IM3-IH"
  },
  {
    "id": 59,
    "category": "exercise",
    "categoryName": "운동·산책",
    "korean": "날씨가 너무 더우면 운동할 의욕이 사라진다.",
    "target": "사라진다",
    "answer": "lose motivation",
    "english": "I lose motivation to exercise when it is too hot.",
    "note": "하려는 의지가 약해지다",
    "level": "IM3-IH"
  },
  {
    "id": 60,
    "category": "exercise",
    "categoryName": "운동·산책",
    "korean": "운동을 마친 뒤에는 충분히 몸을 풀어 준다.",
    "target": "풀어 준다",
    "answer": "stretch",
    "english": "I stretch properly after finishing my workout.",
    "note": "근육을 늘여 몸을 풀다",
    "level": "IM3-IH"
  },
  {
    "id": 61,
    "category": "shopping",
    "categoryName": "쇼핑·패션",
    "korean": "나는 옷을 사기 전에 가격을 여러 곳에서 비교한다.",
    "target": "비교한다",
    "answer": "compare",
    "english": "I compare prices at several stores before buying clothes.",
    "note": "둘 이상의 차이를 살피다",
    "level": "IM3-IH"
  },
  {
    "id": 62,
    "category": "shopping",
    "categoryName": "쇼핑·패션",
    "korean": "온라인 쇼핑은 시간을 절약할 수 있어서 편리하다.",
    "target": "편리하다",
    "answer": "convenient",
    "english": "Online shopping is convenient because it saves time.",
    "note": "이용이나 접근이 쉬울 때",
    "level": "IM3-IH"
  },
  {
    "id": 63,
    "category": "shopping",
    "categoryName": "쇼핑·패션",
    "korean": "사진과 실제 상품의 색상이 조금 달랐다.",
    "target": "달랐다",
    "answer": "different",
    "english": "The color of the actual product was slightly different from the picture.",
    "note": "서로 같지 않을 때",
    "level": "IM3-IH"
  },
  {
    "id": 64,
    "category": "shopping",
    "categoryName": "쇼핑·패션",
    "korean": "옷이 맞지 않아서 다른 사이즈로 교환했다.",
    "target": "교환했다",
    "answer": "exchanged",
    "english": "The clothes did not fit, so I exchanged them for a different size.",
    "note": "구매한 물건을 다른 것으로 바꾸다",
    "level": "IM3-IH"
  },
  {
    "id": 65,
    "category": "shopping",
    "categoryName": "쇼핑·패션",
    "korean": "배송이 예상보다 빨리 도착했다.",
    "target": "도착했다",
    "answer": "arrived",
    "english": "The delivery arrived earlier than expected.",
    "note": "물건이나 사람이 목적지에 오다",
    "level": "IM3-IH"
  },
  {
    "id": 66,
    "category": "shopping",
    "categoryName": "쇼핑·패션",
    "korean": "세일 기간에는 필요 없는 물건까지 사게 된다.",
    "target": "사게 된다",
    "answer": "end up buying",
    "english": "During sales, I end up buying things I do not need.",
    "note": "의도하지 않았지만 결국 하게 되다",
    "level": "IM3-IH"
  },
  {
    "id": 67,
    "category": "shopping",
    "categoryName": "쇼핑·패션",
    "korean": "이 신발은 디자인은 예쁘지만 오래 걸으면 불편하다.",
    "target": "불편하다",
    "answer": "uncomfortable",
    "english": "These shoes look nice, but they are uncomfortable for long walks.",
    "note": "신체적으로 편하지 않을 때",
    "level": "IM3-IH"
  },
  {
    "id": 68,
    "category": "shopping",
    "categoryName": "쇼핑·패션",
    "korean": "나는 유행보다 나에게 잘 어울리는 옷을 고른다.",
    "target": "고른다",
    "answer": "choose",
    "english": "I choose clothes that suit me rather than following trends.",
    "note": "여러 대상 중 선택하다",
    "level": "IM3-IH"
  },
  {
    "id": 69,
    "category": "shopping",
    "categoryName": "쇼핑·패션",
    "korean": "구매 후기들이 상품을 결정하는 데 큰 도움이 된다.",
    "target": "도움이 된다",
    "answer": "helpful",
    "english": "Customer reviews are very helpful when deciding on a product.",
    "note": "판단이나 행동에 유용할 때",
    "level": "IM3-IH"
  },
  {
    "id": 70,
    "category": "shopping",
    "categoryName": "쇼핑·패션",
    "korean": "환불 절차가 생각보다 복잡했다.",
    "target": "복잡했다",
    "answer": "complicated",
    "english": "The refund process was more complicated than I expected.",
    "note": "단계가 많고 이해하기 어려울 때",
    "level": "IM3-IH"
  },
  {
    "id": 71,
    "category": "work",
    "categoryName": "직장·학교",
    "korean": "회의가 예상보다 오래 걸렸다.",
    "target": "걸렸다",
    "answer": "took",
    "english": "The meeting took longer than expected.",
    "note": "시간이 소요되다",
    "level": "IM3-IH"
  },
  {
    "id": 72,
    "category": "work",
    "categoryName": "직장·학교",
    "korean": "나는 중요한 업무부터 먼저 처리한다.",
    "target": "처리한다",
    "answer": "handle",
    "english": "I handle important tasks first.",
    "note": "문제나 업무를 맡아 처리하다",
    "level": "IM3-IH"
  },
  {
    "id": 73,
    "category": "work",
    "categoryName": "직장·학교",
    "korean": "동료와 역할을 나누면 일을 더 효율적으로 할 수 있다.",
    "target": "효율적으로 할 수 있다",
    "answer": "efficiently",
    "english": "We can work more efficiently when we divide roles with coworkers.",
    "note": "시간과 노력을 낭비하지 않게",
    "level": "IM3-IH"
  },
  {
    "id": 74,
    "category": "work",
    "categoryName": "직장·학교",
    "korean": "갑자기 일정이 바뀌어서 계획을 다시 조정했다.",
    "target": "조정했다",
    "answer": "adjusted",
    "english": "The schedule changed suddenly, so I adjusted my plan.",
    "note": "상황에 맞게 조금 변경하다",
    "level": "IM3-IH"
  },
  {
    "id": 75,
    "category": "work",
    "categoryName": "직장·학교",
    "korean": "발표 전에 자료를 여러 번 검토했다.",
    "target": "검토했다",
    "answer": "reviewed",
    "english": "I reviewed the materials several times before the presentation.",
    "note": "내용을 다시 살펴보다",
    "level": "IM3-IH"
  },
  {
    "id": 76,
    "category": "work",
    "categoryName": "직장·학교",
    "korean": "처음 맡은 업무라서 시간이 조금 더 필요했다.",
    "target": "필요했다",
    "answer": "needed",
    "english": "I needed a little more time because it was my first time doing the task.",
    "note": "무언가가 요구되다",
    "level": "IM3-IH"
  },
  {
    "id": 77,
    "category": "work",
    "categoryName": "직장·학교",
    "korean": "팀원들이 적극적으로 의견을 나눴다.",
    "target": "나눴다",
    "answer": "shared",
    "english": "The team members actively shared their opinions.",
    "note": "정보나 생각을 함께 나누다",
    "level": "IM3-IH"
  },
  {
    "id": 78,
    "category": "work",
    "categoryName": "직장·학교",
    "korean": "그 수업은 실생활에 바로 적용할 수 있어서 유용하다.",
    "target": "유용하다",
    "answer": "practical",
    "english": "The class is practical because I can apply it to real life.",
    "note": "실제 상황에서 쓸모 있을 때",
    "level": "IM3-IH"
  },
  {
    "id": 79,
    "category": "work",
    "categoryName": "직장·학교",
    "korean": "마감이 가까워지면 업무 부담이 커진다.",
    "target": "커진다",
    "answer": "increases",
    "english": "My workload increases as the deadline approaches.",
    "note": "양이나 정도가 증가하다",
    "level": "IM3-IH"
  },
  {
    "id": 80,
    "category": "work",
    "categoryName": "직장·학교",
    "korean": "문제가 생기면 혼자 고민하기보다 도움을 요청한다.",
    "target": "요청한다",
    "answer": "ask for help",
    "english": "When a problem comes up, I ask for help instead of struggling alone.",
    "note": "도움을 부탁하다",
    "level": "IM3-IH"
  },
  {
    "id": 81,
    "category": "weather",
    "categoryName": "날씨·환경",
    "korean": "오늘은 공기가 매우 습하다.",
    "target": "습하다",
    "answer": "humid",
    "english": "The air is very humid today.",
    "note": "공기 중 습기가 많을 때",
    "level": "IM3-IH"
  },
  {
    "id": 82,
    "category": "weather",
    "categoryName": "날씨·환경",
    "korean": "아침저녁으로는 날씨가 꽤 쌀쌀하다.",
    "target": "쌀쌀하다",
    "answer": "chilly",
    "english": "It is quite chilly in the morning and evening.",
    "note": "약간 춥고 서늘할 때",
    "level": "IM3-IH"
  },
  {
    "id": 83,
    "category": "weather",
    "categoryName": "날씨·환경",
    "korean": "갑자기 소나기가 내려 옷이 완전히 젖었다.",
    "target": "젖었다",
    "answer": "got soaked",
    "english": "I got completely soaked in a sudden shower.",
    "note": "물에 흠뻑 젖다",
    "level": "IM3-IH"
  },
  {
    "id": 84,
    "category": "weather",
    "categoryName": "날씨·환경",
    "korean": "날씨가 맑으면 멀리 있는 산까지 보인다.",
    "target": "보인다",
    "answer": "visible",
    "english": "The distant mountains are visible when the weather is clear.",
    "note": "눈으로 볼 수 있을 때",
    "level": "IM3-IH"
  },
  {
    "id": 85,
    "category": "weather",
    "categoryName": "날씨·환경",
    "korean": "요즘은 날씨가 너무 변덕스럽다.",
    "target": "변덕스럽다",
    "answer": "unpredictable",
    "english": "The weather has been very unpredictable lately.",
    "note": "쉽게 바뀌어 예측하기 어려울 때",
    "level": "IM3-IH"
  },
  {
    "id": 86,
    "category": "weather",
    "categoryName": "날씨·환경",
    "korean": "봄에는 미세먼지 때문에 창문을 잘 열지 않는다.",
    "target": "열지 않는다",
    "answer": "keep closed",
    "english": "I keep the windows closed in spring because of fine dust.",
    "note": "닫힌 상태로 유지하다",
    "level": "IM3-IH"
  },
  {
    "id": 87,
    "category": "weather",
    "categoryName": "날씨·환경",
    "korean": "비가 그친 뒤 공기가 훨씬 상쾌해졌다.",
    "target": "상쾌해졌다",
    "answer": "fresh",
    "english": "The air became much fresher after the rain stopped.",
    "note": "깨끗하고 기분 좋을 때",
    "level": "IM3-IH"
  },
  {
    "id": 88,
    "category": "weather",
    "categoryName": "날씨·환경",
    "korean": "여름에는 전기 사용량이 크게 늘어난다.",
    "target": "늘어난다",
    "answer": "rises",
    "english": "Electricity use rises significantly in summer.",
    "note": "수치나 양이 증가하다",
    "level": "IM3-IH"
  },
  {
    "id": 89,
    "category": "weather",
    "categoryName": "날씨·환경",
    "korean": "폭설 때문에 도로가 심하게 막혔다.",
    "target": "막혔다",
    "answer": "was congested",
    "english": "The roads were heavily congested because of the snowstorm.",
    "note": "교통이 붐비고 정체되다",
    "level": "IM3-IH"
  },
  {
    "id": 90,
    "category": "weather",
    "categoryName": "날씨·환경",
    "korean": "환경을 위해 일회용품 사용을 줄이려고 한다.",
    "target": "줄이려고 한다",
    "answer": "cut down on",
    "english": "I try to cut down on disposable products for the environment.",
    "note": "사용량이나 소비를 줄이다",
    "level": "IM3-IH"
  },
  {
    "id": 91,
    "category": "problem",
    "categoryName": "문제·해결",
    "korean": "휴대폰이 갑자기 작동하지 않아 매우 당황했다.",
    "target": "당황했다",
    "answer": "panicked",
    "english": "I panicked when my phone suddenly stopped working.",
    "note": "갑작스러운 일에 크게 당황하다",
    "level": "IM3-IH"
  },
  {
    "id": 92,
    "category": "problem",
    "categoryName": "문제·해결",
    "korean": "인터넷 연결이 자꾸 끊겼다.",
    "target": "끊겼다",
    "answer": "kept dropping",
    "english": "The internet connection kept dropping.",
    "note": "연결이 반복해서 끊기다",
    "level": "IM3-IH"
  },
  {
    "id": 93,
    "category": "problem",
    "categoryName": "문제·해결",
    "korean": "예약 내용이 잘못되어 직원에게 문제를 설명했다.",
    "target": "설명했다",
    "answer": "explained",
    "english": "The reservation was incorrect, so I explained the problem to the staff.",
    "note": "상황을 이해할 수 있게 말하다",
    "level": "IM3-IH"
  },
  {
    "id": 94,
    "category": "problem",
    "categoryName": "문제·해결",
    "korean": "직원이 바로 다른 해결책을 제안했다.",
    "target": "제안했다",
    "answer": "suggested",
    "english": "The staff member immediately suggested another solution.",
    "note": "아이디어나 방법을 제시하다",
    "level": "IM3-IH"
  },
  {
    "id": 95,
    "category": "problem",
    "categoryName": "문제·해결",
    "korean": "문제가 예상보다 빨리 해결되었다.",
    "target": "해결되었다",
    "answer": "was resolved",
    "english": "The problem was resolved sooner than expected.",
    "note": "문제가 처리되어 끝나다",
    "level": "IM3-IH"
  },
  {
    "id": 96,
    "category": "problem",
    "categoryName": "문제·해결",
    "korean": "결제 오류로 같은 금액이 두 번 청구되었다.",
    "target": "청구되었다",
    "answer": "was charged",
    "english": "I was charged the same amount twice because of a payment error.",
    "note": "비용이 결제 대상으로 부과되다",
    "level": "IM3-IH"
  },
  {
    "id": 97,
    "category": "problem",
    "categoryName": "문제·해결",
    "korean": "나는 영수증을 보여 주고 환불을 요청했다.",
    "target": "요청했다",
    "answer": "asked for a refund",
    "english": "I showed the receipt and asked for a refund.",
    "note": "지불한 돈을 돌려달라고 요청하다",
    "level": "IM3-IH"
  },
  {
    "id": 98,
    "category": "problem",
    "categoryName": "문제·해결",
    "korean": "약속 시간에 늦을 것 같아 친구에게 미리 연락했다.",
    "target": "연락했다",
    "answer": "let my friend know",
    "english": "I let my friend know in advance that I might be late.",
    "note": "상대에게 정보를 알려 주다",
    "level": "IM3-IH"
  },
  {
    "id": 99,
    "category": "problem",
    "categoryName": "문제·해결",
    "korean": "예상치 못한 상황에서도 침착함을 유지하려고 했다.",
    "target": "유지하려고 했다",
    "answer": "stay calm",
    "english": "I tried to stay calm even in an unexpected situation.",
    "note": "흥분하지 않고 차분하게 있다",
    "level": "IM3-IH"
  },
  {
    "id": 100,
    "category": "problem",
    "categoryName": "문제·해결",
    "korean": "결국 계획을 취소하는 대신 다른 방법을 찾아냈다.",
    "target": "찾아냈다",
    "answer": "figured out",
    "english": "In the end, I figured out another way instead of canceling the plan.",
    "note": "생각 끝에 방법이나 답을 찾아내다",
    "level": "IM3-IH"
  },
  {
    "id": 101,
    "category": "feelings",
    "categoryName": "감정·묘사",
    "korean": "오랜만에 친구를 만나서 정말 반가웠다.",
    "target": "반가웠다",
    "answer": "glad",
    "english": "I was really glad to see my friend after a long time.",
    "note": "누군가를 만나거나 좋은 일로 기쁠 때",
    "level": "IM3-IH"
  },
  {
    "id": 102,
    "category": "feelings",
    "categoryName": "감정·묘사",
    "korean": "중요한 발표를 앞두고 조금 긴장했다.",
    "target": "긴장했다",
    "answer": "nervous",
    "english": "I was a little nervous before an important presentation.",
    "note": "불안하고 긴장될 때",
    "level": "IM3-IH"
  },
  {
    "id": 103,
    "category": "feelings",
    "categoryName": "감정·묘사",
    "korean": "계획한 일을 끝내고 나니 매우 뿌듯했다.",
    "target": "뿌듯했다",
    "answer": "proud",
    "english": "I felt proud after finishing what I had planned.",
    "note": "성취에 만족하고 자랑스러울 때",
    "level": "IM3-IH"
  },
  {
    "id": 104,
    "category": "feelings",
    "categoryName": "감정·묘사",
    "korean": "기대했던 행사가 취소되어 아쉬웠다.",
    "target": "아쉬웠다",
    "answer": "disappointed",
    "english": "I was disappointed that the event I had been looking forward to was canceled.",
    "note": "기대와 달라 실망했을 때",
    "level": "IM3-IH"
  },
  {
    "id": 105,
    "category": "feelings",
    "categoryName": "감정·묘사",
    "korean": "그곳은 조명이 은은해서 분위기가 편안했다.",
    "target": "편안했다",
    "answer": "relaxing",
    "english": "The place had soft lighting, so the atmosphere was relaxing.",
    "note": "사람을 편안하게 만드는 분위기",
    "level": "IM3-IH"
  },
  {
    "id": 106,
    "category": "feelings",
    "categoryName": "감정·묘사",
    "korean": "처음 가 본 곳이라 모든 것이 낯설었다.",
    "target": "낯설었다",
    "answer": "unfamiliar",
    "english": "Everything felt unfamiliar because it was my first time there.",
    "note": "익숙하지 않을 때",
    "level": "IM3-IH"
  },
  {
    "id": 107,
    "category": "feelings",
    "categoryName": "감정·묘사",
    "korean": "친구가 내 말을 진지하게 들어 줘서 고마웠다.",
    "target": "고마웠다",
    "answer": "grateful",
    "english": "I was grateful that my friend listened to me seriously.",
    "note": "도움이나 배려에 감사할 때",
    "level": "IM3-IH"
  },
  {
    "id": 108,
    "category": "feelings",
    "categoryName": "감정·묘사",
    "korean": "예상보다 결과가 좋아서 매우 안도했다.",
    "target": "안도했다",
    "answer": "relieved",
    "english": "I was very relieved because the result was better than expected.",
    "note": "걱정이 사라져 마음이 놓일 때",
    "level": "IM3-IH"
  },
  {
    "id": 109,
    "category": "feelings",
    "categoryName": "감정·묘사",
    "korean": "사람들 앞에서 실수해서 조금 창피했다.",
    "target": "창피했다",
    "answer": "embarrassed",
    "english": "I was a little embarrassed because I made a mistake in front of people.",
    "note": "실수 등으로 민망할 때",
    "level": "IM3-IH"
  },
  {
    "id": 110,
    "category": "feelings",
    "categoryName": "감정·묘사",
    "korean": "반복되는 일상에서 벗어나니 기분이 새로웠다.",
    "target": "새로웠다",
    "answer": "refreshing",
    "english": "It felt refreshing to get away from my repetitive routine.",
    "note": "새롭고 기분 전환이 될 때",
    "level": "IM3-IH"
  },
  {
    "id": 111,
    "category": "tech",
    "categoryName": "휴대폰·인터넷",
    "korean": "이 앱은 화면 구성이 단순해서 사용하기 쉽다.",
    "target": "쉽다",
    "answer": "easy to use",
    "english": "This app is easy to use because its layout is simple.",
    "note": "사용법이 어렵지 않을 때",
    "level": "IM3-IH"
  },
  {
    "id": 112,
    "category": "tech",
    "categoryName": "휴대폰·인터넷",
    "korean": "사진이 너무 많아서 저장 공간이 부족하다.",
    "target": "부족하다",
    "answer": "running out of",
    "english": "I am running out of storage space because I have too many photos.",
    "note": "남은 양이 거의 없을 때",
    "level": "IM3-IH"
  },
  {
    "id": 113,
    "category": "tech",
    "categoryName": "휴대폰·인터넷",
    "korean": "중요한 파일은 클라우드에 따로 백업한다.",
    "target": "백업한다",
    "answer": "back up",
    "english": "I back up important files to the cloud.",
    "note": "복구할 수 있도록 복사해 두다",
    "level": "IM3-IH"
  },
  {
    "id": 114,
    "category": "tech",
    "categoryName": "휴대폰·인터넷",
    "korean": "휴대폰을 새것으로 바꾼 뒤 데이터도 모두 옮겼다.",
    "target": "옮겼다",
    "answer": "transferred",
    "english": "I transferred all my data after getting a new phone.",
    "note": "데이터나 물건을 다른 곳으로 이동하다",
    "level": "IM3-IH"
  },
  {
    "id": 115,
    "category": "tech",
    "categoryName": "휴대폰·인터넷",
    "korean": "공공 와이파이는 연결이 자주 불안정하다.",
    "target": "불안정하다",
    "answer": "unstable",
    "english": "Public Wi-Fi connections are often unstable.",
    "note": "상태가 일정하지 않을 때",
    "level": "IM3-IH"
  },
  {
    "id": 116,
    "category": "tech",
    "categoryName": "휴대폰·인터넷",
    "korean": "알림이 너무 많아서 일부 앱의 알림을 껐다.",
    "target": "껐다",
    "answer": "turned off",
    "english": "I turned off notifications for some apps because there were too many.",
    "note": "기능이나 기기를 끄다",
    "level": "IM3-IH"
  },
  {
    "id": 117,
    "category": "tech",
    "categoryName": "휴대폰·인터넷",
    "korean": "화상 통화 덕분에 멀리 있는 가족과 계속 연락할 수 있다.",
    "target": "연락할 수 있다",
    "answer": "keep in touch",
    "english": "Video calls help me keep in touch with family members who live far away.",
    "note": "관계를 유지하며 연락하다",
    "level": "IM3-IH"
  },
  {
    "id": 118,
    "category": "tech",
    "categoryName": "휴대폰·인터넷",
    "korean": "새 업데이트를 설치한 뒤 속도가 더 빨라졌다.",
    "target": "빨라졌다",
    "answer": "faster",
    "english": "The phone became faster after I installed the new update.",
    "note": "속도가 증가했을 때",
    "level": "IM3-IH"
  },
  {
    "id": 119,
    "category": "tech",
    "categoryName": "휴대폰·인터넷",
    "korean": "비밀번호를 여러 번 틀려 계정이 잠시 잠겼다.",
    "target": "잠겼다",
    "answer": "was locked",
    "english": "My account was temporarily locked because I entered the wrong password several times.",
    "note": "접근이 제한되다",
    "level": "IM3-IH"
  },
  {
    "id": 120,
    "category": "tech",
    "categoryName": "휴대폰·인터넷",
    "korean": "온라인으로 필요한 정보를 바로 찾을 수 있다.",
    "target": "찾을 수 있다",
    "answer": "look up",
    "english": "I can look up the information I need online right away.",
    "note": "정보를 검색해서 찾다",
    "level": "IM3-IH"
  }
];